lalo_usuarios:
    resource: "@LaloBundle/Resources/config/routing/usuarios.yml"
    prefix:   /usuarios
lalo_direcciones:
        resource: "@LaloBundle/Resources/config/routing/direcciones.yml"
        prefix:   /direcciones


lalo_homepage:
    path:     /
    defaults: { _controller: LaloBundle:Default:index }
